// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onzebxpgxwlbvozbvzeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uemVieHBneHdsYnZvemJ2emVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjM5OTcsImV4cCI6MjA2MTYzOTk5N30.C_na06pmMIWYy1ac-c1cg3-astrO-0_NJLP4Ak2ijL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);